import ROOT


ROOT.gROOT.SetBatch(1)
ROOT.gStyle.SetOptFit(0)
ROOT.gStyle.SetOptStat(0)
# ROOT.gStyle.SetPalette(ROOT.kRust)
# ROOT.gStyle.SetPalette(ROOT.kSolar)
# ROOT.gStyle.SetPalette(ROOT.kInvertedDarkBodyRadiator)
ROOT.gStyle.SetPalette(ROOT.kDarkBodyRadiator)
# ROOT.gStyle.SetPalette(ROOT.kRainbow)
ROOT.gStyle.SetPadBottomMargin(0.15)
ROOT.gStyle.SetPadLeftMargin(0.13)
ROOT.gStyle.SetPadRightMargin(0.16)

detectors = ["ALPIDE_0","ALPIDE_1","ALPIDE_2","ALPIDE_3","ALPIDE_4"]

def h1h2max(h1,h2):
    hmax = -1
    y1 = h1.GetMaximum()
    y2 = h2.GetMaximum()
    hmax = y1 if(y1>y2) else y2
    return hmax


f = ROOT.TFile("scan.root","READ")
# f = ROOT.TFile("scan_nodxdycut.root","READ")

leg = ROOT.TLegend(0.6,0.7,0.95,0.8)
leg.SetFillStyle(4000) # will be transparent
leg.SetFillColor(0)
leg.SetTextFont(42)
leg.SetTextSize(0.037)
leg.SetBorderSize(0)

cnv = ROOT.TCanvas("cnv","",1800,1000)
cnv.Divide(3,2)
for idet,det in enumerate(detectors):
    cnv.cd(idet+1)
    ROOT.gPad.SetTicks(1,1)
    hx = f.Get(f"h_residual_x_mid_{det}")
    hy = f.Get(f"h_residual_y_mid_{det}")
    hx.GetXaxis().SetTitle("k_{trk}-k_{cls} [mm]")
    hy.GetXaxis().SetTitle("k_{trk}-k_{cls} [mm]")
    hx.SetTitle(f"{det}")
    hy.SetTitle(f"{det}")
    hmax = h1h2max(hx,hy)
    hx.SetMaximum(1.05*hmax)
    hy.SetMaximum(1.05*hmax)
    hx.SetLineColor(ROOT.kBlack)
    hy.SetLineColor(ROOT.kRed)
    hx.Draw("hist")
    hy.Draw("hist same")
    if(idet==0):
        leg.AddEntry(hx,"k=x","l")
        leg.AddEntry(hy,"k=y","l")
    leg.Draw("same")
    ROOT.gPad.RedrawAxis()
cnv.SaveAs("plot_alignment_temp.pdf(")

cnv = ROOT.TCanvas("cnv","",2500,500)
cnv.Divide(5,1)
for idet,det in enumerate(detectors):
    cnv.cd(idet+1)
    ROOT.gPad.SetTicks(1,1)
    hx = f.Get(f"h_residual_x_mid_{det}")
    hy = f.Get(f"h_residual_y_mid_{det}")
    hx.GetXaxis().SetTitle("k_{trk}-k_{cls} [mm]")
    hy.GetXaxis().SetTitle("k_{trk}-k_{cls} [mm]")
    hx.SetTitle(f"{det}")
    hy.SetTitle(f"{det}")
    hmax = h1h2max(hx,hy)
    hx.SetMaximum(1.05*hmax)
    hy.SetMaximum(1.05*hmax)
    hx.SetLineColor(ROOT.kBlack)
    hy.SetLineColor(ROOT.kRed)
    hx.Draw("hist")
    hy.Draw("hist same")
    leg.Draw("same")
    ROOT.gPad.RedrawAxis()
cnv.SaveAs("plot_alignment_temp.pdf")


cnv = ROOT.TCanvas("cnv","",1800,1000)
cnv.Divide(3,2)
for idet,det in enumerate(detectors):
    cnv.cd(idet+1)
    ROOT.gPad.SetTicks(1,1)
    h = f.Get(f"h_residual_xy_mid_{det}")
    h.GetZaxis().SetTitleOffset(1.3)
    h.Draw("colz")
    ROOT.gPad.RedrawAxis()
cnv.SaveAs("plot_alignment_temp.pdf")

cnv = ROOT.TCanvas("cnv","",2500,500)
cnv.Divide(5,1)
for idet,det in enumerate(detectors):
    cnv.cd(idet+1)
    ROOT.gPad.SetTicks(1,1)
    h = f.Get(f"h_residual_xy_mid_{det}")
    h.GetZaxis().SetTitleOffset(1.3)
    h.Draw("colz")
    ROOT.gPad.RedrawAxis()
cnv.SaveAs("plot_alignment_temp.pdf")


cnv = ROOT.TCanvas("cnv","",1800,1000)
cnv.Divide(3,2)
for idet,det in enumerate(detectors):
    cnv.cd(idet+1)
    ROOT.gPad.SetTicks(1,1)
    hx = f.Get(f"dx_{det}")
    hy = f.Get(f"dy_{det}")
    hx.GetXaxis().SetTitle("dk [mm]")
    hy.GetXaxis().SetTitle("dk [mm]")
    hx.GetYaxis().SetTitle("#Sigma#Deltak [mm]")
    hy.GetYaxis().SetTitle("#Sigma#Deltak [mm]")
    hx.SetTitle(f"{det}")
    hy.SetTitle(f"{det}")
    hmax = h1h2max(hx,hy)
    hx.SetMaximum(1.05*hmax)
    hy.SetMaximum(1.05*hmax)
    hx.SetLineColor(ROOT.kBlack)
    hy.SetLineColor(ROOT.kRed)
    hx.Draw("hist")
    hy.Draw("hist same")
    hx.SetMinimum(0)
    hy.SetMinimum(0)
    leg.Draw("same")
    ROOT.gPad.RedrawAxis()
cnv.SaveAs("plot_alignment_temp.pdf")

cnv = ROOT.TCanvas("cnv","",2500,500)
cnv.Divide(5,1)
for idet,det in enumerate(detectors):
    cnv.cd(idet+1)
    ROOT.gPad.SetTicks(1,1)
    hx = f.Get(f"dx_{det}")
    hy = f.Get(f"dy_{det}")
    hx.GetXaxis().SetTitle("dk [mm]")
    hy.GetXaxis().SetTitle("dk [mm]")
    hx.GetYaxis().SetTitle("#Sigma#Deltak [mm]")
    hy.GetYaxis().SetTitle("#Sigma#Deltak [mm]")
    hx.SetTitle(f"{det}")
    hy.SetTitle(f"{det}")
    hmax = h1h2max(hx,hy)
    hx.SetMaximum(1.05*hmax)
    hy.SetMaximum(1.05*hmax)
    hx.SetLineColor(ROOT.kBlack)
    hy.SetLineColor(ROOT.kRed)
    hx.Draw("hist")
    hy.Draw("hist same")
    hx.SetMinimum(0)
    hy.SetMinimum(0)
    leg.Draw("same")
    ROOT.gPad.RedrawAxis()
cnv.SaveAs("plot_alignment_temp.pdf")

cnv = ROOT.TCanvas("cnv","",1800,1000)
cnv.Divide(3,2)
for idet,det in enumerate(detectors):
    cnv.cd(idet+1)
    ROOT.gPad.SetTicks(1,1)
    h = f.Get(f"dt_{det}")
    h.SetTitle(f"{det}")
    h.GetYaxis().SetTitle("#Sigma#theta [rad]")
    h.SetLineColor(ROOT.kBlack)
    h.SetMinimum(0)
    h.Draw("hist")
    ROOT.gPad.RedrawAxis()
cnv.SaveAs("plot_alignment_temp.pdf")

cnv = ROOT.TCanvas("cnv","",2500,500)
cnv.Divide(5,1)
for idet,det in enumerate(detectors):
    cnv.cd(idet+1)
    ROOT.gPad.SetTicks(1,1)
    h = f.Get(f"dt_{det}")
    h.SetTitle(f"{det}")
    h.GetYaxis().SetTitle("#Sigma#theta [rad]")
    h.SetLineColor(ROOT.kBlack)
    h.SetMinimum(0)
    h.Draw("hist")
    ROOT.gPad.RedrawAxis()
cnv.SaveAs("plot_alignment_temp.pdf)")
